[deploy]
bucket = 'cfn-artifacts-ewn'
region = 'us-east-1'
stack_name = 'CrdSrvBackendFlask'

[parameters]
EnvFrontendUrl = 'https://cruddur.info'
EnvBackendUrl = 'https://api.cruddur.info'
DDBMessageTable = 'CrdDdb-DynamoDBTable-1XP2RIF6G70MT'