#!/usr/bin/env python3
import os
import sys
import glob
import re
import time
import importlib


current_path = os.path.dirname(os.path.abspath(__file__))
parent_path = os.path.abspath(os.path.join(current_path, '..', '..','backend-flask'))
sys.path.append(parent_path)

migrations_path = os.path.abspath(os.path.join(current_path, '..', '..','backend-flask','db','migrations'))
print(migrations_path)
sys.path.append(migrations_path)
migration_files = glob.glob(f"{migrations_path}/*")
print(migration_files)

for migration_file in migration_files:
    print(migration_file)





