[deploy]
bucket = 'cfn-artifacts-ewn'
region = 'us-east-1'
stack_name = 'CrdFrontend'

[parameters]
CertificateArn = 'arn:aws:acm:us-east-1:088478797243:certificate/d704f33a-3ae7-498f-ae1c-8571f309a097'
WwwBucketName = 'www.cruddur.info'
RootBucketName = 'cruddur.info'